# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1184, 775)
        MainWindow.setStyleSheet("background-color: rgb(31, 1, 94);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 85))
        self.groupBox_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(31, 1, 94);\n"
"font: 75 14pt \"Aharoni\";")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setStyleSheet("")
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 500))
        self.groupBox_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(31, 1, 94);\n"
"font: 75 10pt \"Aharoni\";")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_img1 = QtWidgets.QLabel(self.groupBox_2)
        self.label_img1.setMinimumSize(QtCore.QSize(500, 0))
        self.label_img1.setMaximumSize(QtCore.QSize(500, 16777215))
        self.label_img1.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_img1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_img1.setObjectName("label_img1")
        self.horizontalLayout_2.addWidget(self.label_img1)
        self.label_img2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_img2.setMinimumSize(QtCore.QSize(500, 0))
        self.label_img2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.label_img2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_img2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_img2.setObjectName("label_img2")
        self.horizontalLayout_2.addWidget(self.label_img2)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 132))
        self.groupBox.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(31, 1, 94);\n"
"font: 75 10pt \"Aharoni\";")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.radioButton_img = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_img.setMinimumSize(QtCore.QSize(0, 30))
        self.radioButton_img.setChecked(True)
        self.radioButton_img.setObjectName("radioButton_img")
        self.horizontalLayout_3.addWidget(self.radioButton_img)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.radioButton_video = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_video.setMinimumSize(QtCore.QSize(0, 30))
        self.radioButton_video.setObjectName("radioButton_video")
        self.horizontalLayout_3.addWidget(self.radioButton_video)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.radioButton_cam = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_cam.setMinimumSize(QtCore.QSize(0, 30))
        self.radioButton_cam.setObjectName("radioButton_cam")
        self.horizontalLayout_3.addWidget(self.radioButton_cam)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_path = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_path.setMinimumSize(QtCore.QSize(0, 38))
        self.lineEdit_path.setStyleSheet("color: rgb(255, 0, 0);")
        self.lineEdit_path.setObjectName("lineEdit_path")
        self.horizontalLayout.addWidget(self.lineEdit_path)
        self.pushButto_select = QtWidgets.QPushButton(self.groupBox)
        self.pushButto_select.setMinimumSize(QtCore.QSize(0, 38))
        self.pushButto_select.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.pushButto_select.setObjectName("pushButto_select")
        self.horizontalLayout.addWidget(self.pushButto_select)
        self.pushButton_run = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_run.setMinimumSize(QtCore.QSize(0, 38))
        self.pushButton_run.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.pushButton_run.setObjectName("pushButton_run")
        self.horizontalLayout.addWidget(self.pushButton_run)
        self.pushButton_close = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_close.setMinimumSize(QtCore.QSize(0, 38))
        self.pushButton_close.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"")
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayout.addWidget(self.pushButton_close)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1184, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "行人安全检测系统"))
        self.groupBox_2.setTitle(_translate("MainWindow", "显示区域"))
        self.label_img1.setText(_translate("MainWindow", "原始画面"))
        self.label_img2.setText(_translate("MainWindow", "识别画面"))
        self.radioButton_img.setText(_translate("MainWindow", "图片文件"))
        self.radioButton_video.setText(_translate("MainWindow", "视频文件"))
        self.radioButton_cam.setText(_translate("MainWindow", "摄像头"))
        self.label.setText(_translate("MainWindow", "文件路径"))
        self.pushButto_select.setText(_translate("MainWindow", "选择文件"))
        self.pushButton_run.setText(_translate("MainWindow", "打开摄像头"))
        self.pushButton_close.setText(_translate("MainWindow", "退出系统"))

