# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1184, 833)
        MainWindow.setStyleSheet("# background-color: rgb(31, 1, 94);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setMinimumSize(QtCore.QSize(0, 100))
        self.lcdNumber.setMaximumSize(QtCore.QSize(16777215, 100))
        self.lcdNumber.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdNumber.setStyleSheet("color: rgb(255, 0, 0);")
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setObjectName("lcdNumber")
        self.verticalLayout_5.addWidget(self.lcdNumber)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 500))
        self.groupBox_2.setStyleSheet("/*color: rgb(255, 255, 255);\n"
"background-color: rgb(31, 1, 94);*/\n"
"font: 75 10pt \"Aharoni\";")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_img1 = QtWidgets.QLabel(self.groupBox_2)
        self.label_img1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_img1.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_img1.setText("")
        self.label_img1.setObjectName("label_img1")
        self.horizontalLayout.addWidget(self.label_img1)
        self.label_img2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_img2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_img2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_img2.setText("")
        self.label_img2.setObjectName("label_img2")
        self.horizontalLayout.addWidget(self.label_img2)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1184, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_3 = QtWidgets.QMenu(self.menu)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menu)
        self.menu_4.setObjectName("menu_4")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_5 = QtWidgets.QMenu(self.menubar)
        self.menu_5.setObjectName("menu_5")
        self.menu_6 = QtWidgets.QMenu(self.menubar)
        self.menu_6.setObjectName("menu_6")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionopencamera = QtWidgets.QAction(MainWindow)
        self.actionopencamera.setObjectName("actionopencamera")
        self.actionopenCam = QtWidgets.QAction(MainWindow)
        self.actionopenCam.setObjectName("actionopenCam")
        self.actioncloseCam = QtWidgets.QAction(MainWindow)
        self.actioncloseCam.setObjectName("actioncloseCam")
        self.actionopenVideo = QtWidgets.QAction(MainWindow)
        self.actionopenVideo.setObjectName("actionopenVideo")
        self.actioncloseVideo = QtWidgets.QAction(MainWindow)
        self.actioncloseVideo.setObjectName("actioncloseVideo")
        self.actionopenImage = QtWidgets.QAction(MainWindow)
        self.actionopenImage.setObjectName("actionopenImage")
        self.actionbeginRecoding = QtWidgets.QAction(MainWindow)
        self.actionbeginRecoding.setObjectName("actionbeginRecoding")
        self.actionendRecoding = QtWidgets.QAction(MainWindow)
        self.actionendRecoding.setObjectName("actionendRecoding")
        self.actionabout = QtWidgets.QAction(MainWindow)
        self.actionabout.setObjectName("actionabout")
        self.actioninstructions = QtWidgets.QAction(MainWindow)
        self.actioninstructions.setObjectName("actioninstructions")
        self.menu_3.addAction(self.actionopenVideo)
        self.menu_3.addAction(self.actioncloseVideo)
        self.menu_4.addAction(self.actionopenImage)
        self.menu.addAction(self.menu_4.menuAction())
        self.menu.addAction(self.menu_3.menuAction())
        self.menu_2.addAction(self.actionopenCam)
        self.menu_2.addAction(self.actioncloseCam)
        self.menu_5.addAction(self.actionbeginRecoding)
        self.menu_5.addAction(self.actionendRecoding)
        self.menu_6.addAction(self.actionabout)
        self.menu_6.addAction(self.actioninstructions)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())
        self.menubar.addAction(self.menu_6.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "显示区域"))
        self.menu.setTitle(_translate("MainWindow", "离线识别"))
        self.menu_3.setTitle(_translate("MainWindow", "视频文件"))
        self.menu_4.setTitle(_translate("MainWindow", "图片文件"))
        self.menu_2.setTitle(_translate("MainWindow", "在线识别"))
        self.menu_5.setTitle(_translate("MainWindow", "录制"))
        self.menu_6.setTitle(_translate("MainWindow", "帮助"))
        self.actionopencamera.setText(_translate("MainWindow", "打开摄像头"))
        self.actionopenCam.setText(_translate("MainWindow", "打开摄像头"))
        self.actioncloseCam.setText(_translate("MainWindow", "关闭摄像头"))
        self.actionopenVideo.setText(_translate("MainWindow", "打开"))
        self.actioncloseVideo.setText(_translate("MainWindow", "关闭"))
        self.actionopenImage.setText(_translate("MainWindow", "打开"))
        self.actionbeginRecoding.setText(_translate("MainWindow", "开始录制"))
        self.actionendRecoding.setText(_translate("MainWindow", "结束录制"))
        self.actionabout.setText(_translate("MainWindow", "关于"))
        self.actioninstructions.setText(_translate("MainWindow", "使用说明"))

